#%RAML 1.0 Library

usage: |
  import the error type '/types/[raml file]' in your project as type (object)

types:
  error-log: !include types/error-log.raml
  error-eapi: !include types/error-eapi.raml